default_stages: [commit]
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.89.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-no-color
          - --args=-diff
#          - --args=-write=false
#      - id: terraform_validate
      - id: terraform_tflint
        args: [" --recursive"]
#      - id: terraform_tfsec