name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'env/**'
      - 'target.txt'

jobs:
  read_target_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Read target file
        id: target
        run: |
          targets=$(cat target.txt | grep -v "^#" | awk '{print "{\"action\": \""$1"\", \"workdir\": \""$2"\"}"}' | jq -s -c)
          echo "matrix=$targets" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.target.outputs.matrix }}

  plan_and_apply:
    needs: read_target_file
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: ${{ fromJson(needs.read_target_file.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1800

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ matrix.target.workdir }}

      - name: Terraform Plan
        id: plan
        run: |
          if [ "${{ matrix.target.action }}" == "apply" ]; then
            terraform plan -input=false
          elif [ "${{ matrix.target.action }}" == "destroy" ]; then
            terraform plan -destroy -input=false
          else
            echo "Invalid action: ${{ matrix.target.action }}"
            exit 1
          fi
        working-directory: ${{ matrix.target.workdir }}
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform ${{ matrix.target.action }}
        run: |
          if [ "${{ matrix.target.action }}" == "apply" ]; then
            terraform apply -auto-approve
          elif [ "${{ matrix.target.action }}" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            echo "Invalid action: ${{ matrix.target.action }}"
            exit 1
          fi
        working-directory: ${{ matrix.target.workdir }}